### ISSUE TITLE
Getting "Failed to open file writer for verification-2024-04-07..." error

### ISSUE THREAD

**Issue by takanuva15** [ChrisCarini/intellij-platform-plugin-verifier-action#70]
**Describe the bug**
When running the action with the below versions, I get the below error.

Versions:
```
ideaIC:2024.1
ideaIC:241-EAP-SNAPSHOT
pycharmPC:2024.1
pycharmPC:241-EAP-SNAPSHOT
```

Error:
```
2024-04-07T03:07:44 [main] INFO  verification - Finished 1 of 4 verifications (in 3.3 s): PC-241.14494.241 against de.nordgedanken.auto_hotkey:0.10.4: 2 compatibility problems
  2024-04-07T03:07:44 [verifier_4] ERROR c.j.p.reporting.common.FileReporter - Failed to open file writer for verification-2024-04-07 at 03.07.20/PC-241.14494.241/plugins/de.nordgedanken.auto_hotkey/0.10.4/verification-verdict.txt
  java.nio.file.FileAlreadyExistsException: verification-2024-04-07 at 03.07.20/PC-241.14494.241/plugins/de.nordgedanken.auto_hotkey/0.10.4/verification-verdict.txt
  	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
  	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
  	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
  	at java.base/java.nio.file.Files.createFile(Files.java:658)
  	at com.jetbrains.plugin.structure.base.utils.FileUtilKt.create(FileUtil.kt:[73](https://github.com/Nordgedanken/intellij-autohotkey/actions/runs/8585720643/job/23527486867?pr=75#step:5:79))at com.jetbrains.pluginverifier.reporting.common.FileReporter.openFileWriter(FileReporter.kt:31)
  	at com.jetbrains.pluginverifier.reporting.common.FileReporter.report(FileReporter.kt:44)
  	at com.jetbrains.pluginverifier.reporting.DirectoryBasedPluginVerificationReportage.useReporter(DirectoryBasedPluginVerificationReportage.kt:113)
  	at com.jetbrains.pluginverifier.reporting.DirectoryBasedPluginVerificationReportage.reportVerificationDetails(DirectoryBasedPluginVerificationReportage.kt:159)
  	at com.jetbrains.pluginverifier.reporting.DirectoryBasedPluginVerificationReportage.reportVerificationResult(DirectoryBasedPluginVerificationReportage.kt:123)
  	at com.jetbrains.pluginverifier.PluginVerifierRunKt.runSeveralVerifiers$lambda$3$lambda$2(PluginVerifierRun.kt:37)
  	at com.jetbrains.plugin.structure.base.utils.ExecutorWithProgress$TimedCallable.call(ConcurrencyUtils.kt:133)
  	at com.jetbrains.plugin.structure.base.utils.ExecutorWithProgress$TimedCallable.call(ConcurrencyUtils.kt:127)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:[84](https://github.com/Nordgedanken/intellij-autohotkey/actions/runs/8585720643/job/23527486867?pr=75#step:5:90)0)
```
Link to the full original job output: https://github.com/Nordgedanken/intellij-autohotkey/actions/runs/8585720643/job/23527486867?pr=75

**To Reproduce**

This is my yml config:
```yml
    # Run IntelliJ Plugin Verifier action using GitHub Action
    - name: Verify Plugin Compatibility
      id: verify
      uses: ChrisCarini/intellij-platform-plugin-verifier-action@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        plugin-location: '*.zip'
        # NOTE: For ide-versions, we just need to verify IJ community & one non-IJ IDE.
        ide-versions: .github/workflows/ide_versions_to_verify.txt
        failure-levels: |
          COMPATIBILITY_WARNINGS
          COMPATIBILITY_PROBLEMS
          DEPRECATED_API_USAGES
          INTERNAL_API_USAGES
          OVERRIDE_ONLY_API_USAGES
          NON_EXTENDABLE_API_USAGES
          PLUGIN_STRUCTURE_WARNINGS
          MISSING_DEPENDENCIES
          INVALID_PLUGIN
          NOT_DYNAMIC
```

[Link to yml build file in PR](https://github.com/Nordgedanken/intellij-autohotkey/pull/75/files#diff-a097a9bd7c0134687eb5a3e1951468dab7a6486a5c44051ee371402d972d1097)

**Expected behavior**
Should not fail with file write error, but show me actual deprecated APIs instead

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - GitHub actions

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by ChrisCarini** [comment]
Hi again @takanuva15 !

That error looks like it's coming from the verifier itself, and not this action. For context, *this* action writes out to `verification_result.log`, but it will write out the same contents you are seeing in the runner output - the runner output itself is showing the output from invoking the verifier. I believe this issue are seeing should be reported to the verifier itself, and not this action.

Let me know if you believe otherwise; if I don't hear back, I'll go ahead and close out this issue.

Thanks again for being a user, and reporting issues as you encounter them!

Best,
Chris
